const table = {
  'month': {
    '1': 'Mecânico',
    '2': 'Capitão/Capitã',
    '3': 'Eletricista',
    '4': 'Projetista',
    '5': 'Programador(a)',
    '6': 'Escritor(a)',
    '7': 'Fotógrafo(a)',
    '8': 'Apresentador(a)',
    '9': 'Digital Influencer',
    '10': 'Jogador(a) Humano',
    '11': 'Co-piloto',
    '12': 'Piloto',
  },
  'day': {
    '1': 'Rockeiro(a)',
    '2': 'Preguiçoso(a)',
    '3': 'Tagarela',
    '4': 'Traíra',
    '5': 'X9',
    '6': 'Sempre cansado(a)',
    '7': 'Quieto(a)',
    '8': 'Iludido(a)',
    '9': 'Sumido(a)',
    '10': 'Famosinho(a)',
    '11': 'Faladorzinho(a)',
    '12': 'Lerdo(a)',
    '13': 'Ciumento(a)',
    '14': 'Teimoso(a)',
    '15': 'Egoísta(a)',
    '16': 'Inteligente só que não',
    '17': 'Mentiroso(a)',
    '18': 'Crente',
    '19': 'Marrento(a)',
    '20': 'Pagado(a)',
    '21': 'Fotogênico(a)',
    '22': 'Cheio(a) de compromissos',
    '23': 'Esfomiado(a)',
    '24': 'Funkeiro(a)',
    '25': 'Turista',
    '26': 'Mimado(a)',
    '27': 'Atrasado(a)',
    '28': 'Fofoqueiro(a)',
    '29': 'Metido(a)',
    '30': 'Narcisista',
    '31': 'Feio(a)',
  },
  'year': {
    '1994': 'Que vai só pela parceria',
    '1995': 'Que diz que tá na robótica mas não tá',
    '1996': 'Que vai só pela zoeira',
    '1997': 'Que esquece das reuniões',
    '1998': 'Que só atrapalha',
    '1999': 'Que rouba o almoço dos coleguinhas',
    '2000': 'Que tá sempre com fome ',
    '2001': 'Que some nos sábados',
    '2002': 'Que não sabe usar computador',
    '2003': 'Que tá só pelas curtidas no Face',
    '2004': 'Que tá só por viajar pros EUA',
    '2005': 'Que vai pra praia no meio da temporada',
    '2006': 'Que faz arte e põe a culpa nos outros',
    '2007': 'Que sempre tem um aniver pra ir',
  }
}

module.exports = (day, month, year) => {
  return `${table.month[month]} ${table.day[day]} ${table.year[year]}`
}
